// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PosBackend.Models;

#nullable disable

namespace PosBackend.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20241022090329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PosBackend.Models.PricingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<List<string>>("Description")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ExtraDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("TestPeriodDays")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PricingPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = new List<string> { "Select the essential modules and features for your business.", "Ideal for small businesses or those new to POS systems." },
                            ExtraDescription = "This package is perfect for startups and small businesses.",
                            Icon = "starter-icon.png",
                            Price = 29.99m,
                            TestPeriodDays = 14,
                            Title = "Starter"
                        },
                        new
                        {
                            Id = 2,
                            Description = new List<string> { "Expand your business capabilities with advanced modules and features.", "Designed for growing businesses looking to enhance their POS system." },
                            ExtraDescription = "Ideal for businesses looking to scale and grow.",
                            Icon = "growth-icon.png",
                            Price = 59.99m,
                            TestPeriodDays = 14,
                            Title = "Growth"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
