﻿﻿﻿﻿using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PosBackend.Migrations
{
    /// <inheritdoc />
    public partial class AddAddOnsTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Check if AddOns table exists, create only if it doesn't exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'AddOns') THEN
                        CREATE TABLE ""AddOns"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""Name"" text NOT NULL,
                            ""Description"" text NOT NULL,
                            ""Price"" numeric NOT NULL,
                            CONSTRAINT ""PK_AddOns"" PRIMARY KEY (""Id"")
                        );
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AddOns");
        }
    }
}
