// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PosBackend.Models;

#nullable disable

namespace PosBackend.Migrations
{
    [DbContext(typeof(PosDbContext))]
    partial class PosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PosBackend.Models.PricingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExtraDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("TestPeriodDays")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PricingPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Select the essential modules and features for your business.;Ideal for small businesses or those new to POS systems.",
                            ExtraDescription = "This package is perfect for startups and small businesses.",
                            Icon = "starter-icon.png",
                            Price = 29.99m,
                            TestPeriodDays = 14,
                            Title = "Starter"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Expand your business capabilities with advanced modules and features.;Designed for growing businesses looking to enhance their POS system.",
                            ExtraDescription = "Ideal for businesses looking to scale and grow.",
                            Icon = "growth-icon.png",
                            Price = 59.99m,
                            TestPeriodDays = 14,
                            Title = "Growth"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tailor-made solutions for your unique business needs.;Perfect for businesses requiring customized POS features.",
                            ExtraDescription = "Get a POS system that fits your specific requirements.",
                            Icon = "custom-icon.png",
                            Price = 99.99m,
                            TestPeriodDays = 30,
                            Title = "Custom"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comprehensive POS solutions for large enterprises.;Includes all advanced features and premium support.",
                            ExtraDescription = "Ideal for large businesses with extensive POS needs.",
                            Icon = "enterprise-icon.png",
                            Price = 199.99m,
                            TestPeriodDays = 30,
                            Title = "Enterprise"
                        },
                        new
                        {
                            Id = 5,
                            Description = "All-inclusive POS package with premium features.;Best for businesses looking for top-tier POS solutions.",
                            ExtraDescription = "Experience the best POS system with all features included.",
                            Icon = "premium-icon.png",
                            Price = 299.99m,
                            TestPeriodDays = 30,
                            Title = "Premium"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
